### ISSUE TITLE
Documentation of all the completed components of the  building i.e  Bush clearance, Digging the foundation, Raising the Foundation and etc

### ISSUE THREAD

**Issue by PyGamma** [The-Youth-Empowerment-Foundation-Adju/Pagirinya-Satellite-House#3]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by PyGamma** [comment]
This is coming up soon..

**Comment by Ira13637** [comment]
I don't understand this part of the communication.

**Comment by gibertgibs** [comment]
Ohhh that will be an added advantage to the purpose of the Project.

**Comment by PyGamma** [comment]
@gibertgibs Can you please add the picture for bush clearing in the file meant for it.
