### ISSUE TITLE
Upload of images of the bush clearance and foundation setting.

### ISSUE THREAD

**Issue by PyGamma** [The-Youth-Empowerment-Foundation-Adju/Pagirinya-Satellite-House#4]
@gibertgibs and @vugawilliam, can you guys upload the images taken during bush clearance and setting of the foundation

**Comment by gibertgibs** [comment]
![400086600740_319797](https://user-images.githubusercontent.com/69734297/115503318-e6ff4480-a27e-11eb-8f0c-3135c0953b41.jpg)
![400086500603_318894](https://user-images.githubusercontent.com/69734297/115503326-e9619e80-a27e-11eb-9562-cf4c20266aad.jpg)

**Comment by gibertgibs** [comment]
this is the only photos taken during the bush clearance.....

**Comment by Ira13637** [comment]
@gibertgibs @PyGamma forwarded some to the tele group.

**Comment by gibertgibs** [comment]
It has been done....

**Comment by PyGamma** [comment]
Executed
