### ISSUE TITLE
A catchline for a poster about the online repository and collaboration

### ISSUE THREAD

**Issue by timmwille** [The-Youth-Empowerment-Foundation-Adju/Pagirinya-Satellite-House#7]
I was thinking about something like:

>**"To Co-Create on planning, innovation in progress and ways to replicate such kind of constructions in other refugee settlements: join the open source media collaboration on GitHub"**

and [add QR Code + URL] 

what do you think?

**Comment by timmwille** [comment]
@intertwilight @PyGamma @vugawilliam @gibertgibs would be nice to get your feedback on this

**Comment by heikeNL** [comment]
I miss the words media architecture, prototype,  sharing of digital  knowledge concerning architecture... open source context... support refugees... digital innovation....

**Comment by PyGamma** [comment]
Here comes my suggestion which is a little aligned with previous views.
To collaborate in the creating and designing of  open source resources for prototyping media based architecture

**Comment by gibertgibs** [comment]
Mr. Timm I think Gama has a point on his view, it will be great if we adopt the view of prototyping media based architecture by designing open source resources which will give it a upper hand to involve many into to collaborate.

**Comment by timmwille** [comment]
good to go @heikeNL got it, I will add the poster ASAP when ready via Pull Request thank you guys also check out my PR #10
