### ISSUE TITLE
Please remove Security restrictions and Issue Templates

### ISSUE THREAD

**Issue by timmwille** [The-Youth-Empowerment-Foundation-Adju/Pagirinya-Satellite-House#8]
1. one can not send a Pull Request because of this Security thing
2. in is in conflict with the License
3. The Issue Template is confusing, as it is for Software rather then house building

**Comment by timmwille** [comment]
would be nice to merge those changes:
https://github.com/The-Youth-Empowerment-Foundation-Adju/Pagirinya-Satellite-House/compare/main...intertwilight:patch-1

**Comment by PyGamma** [comment]
Done
